name: "Workflow : Pull Request"

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:  # workflow_dispatch 호출

jobs:
  pr-integration-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Launch test DB
        run: docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=1234 -e MYSQL_DATABASE=poppin mysql:8

      - name: Test with Gradle
        run: |
          ./gradlew test
