name: "Workflow : Push"

on:
  push:
    branches:
      - main
  workflow_dispatch:  # workflow_dispatch 호출

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build with Jib
        run: |
          ./gradlew jib
      
      - name: Rollout Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment ${{ secrets.KUBE_DEPLOYMENT_NAME }} -n ${{ secrets.KUBE_NAMESPACE }}